pipeline {
    agent any
        tools {nodejs "nodejs"}
        environment{
            CI = 'false'
        }
    
    stages{
        stage('NPM Build'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: '5ddba508-4ae2-4c00-ba42-c95ac41a7603', url: 'https://github.com/Sakthi2kx/springboot-react-project.git']]])
                dir('polling-app-client'){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t sakthi2kx/survey-client ./polling-app-client'
                }
            }
        }
        stage('Push image to Hub'){
            steps{
                script{
                   withCredentials([string(credentialsId: 'docker-hub-password', variable: 'docker-hub-password')]) {
                   bat 'docker login -u sakthi2kx -p admin@123'
                    }
                   bat 'docker push sakthi2kx/survey-client'
                }
            }
        }
    }    
}
